In [1]:
#Import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Import .csv file and convert it to a DataFrame object
df = pd.read_csv("Wholesale customers data.csv");

print(df.head())


   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185


In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB
None


In [4]:
df.drop(['Channel','Region'],axis=1,inplace=True)

In [5]:
array=df.values

In [6]:
array

array([[12669,  9656,  7561,   214,  2674,  1338],
       [ 7057,  9810,  9568,  1762,  3293,  1776],
       [ 6353,  8808,  7684,  2405,  3516,  7844],
       ...,
       [14531, 15488, 30243,   437, 14841,  1867],
       [10290,  1981,  2232,  1038,   168,  2125],
       [ 2787,  1698,  2510,    65,   477,    52]], dtype=int64)

In [7]:
stscaler = StandardScaler().fit(array)
X = stscaler.transform(array)

In [8]:
X

array([[ 0.05293319,  0.52356777, -0.04111489, -0.58936716, -0.04356873,
        -0.06633906],
       [-0.39130197,  0.54445767,  0.17031835, -0.27013618,  0.08640684,
         0.08915105],
       [-0.44702926,  0.40853771, -0.0281571 , -0.13753572,  0.13323164,
         2.24329255],
       ...,
       [ 0.20032554,  1.31467078,  2.34838631, -0.54337975,  2.51121768,
         0.12145607],
       [-0.13538389, -0.51753572, -0.60251388, -0.41944059, -0.56977032,
         0.21304614],
       [-0.72930698, -0.5559243 , -0.57322717, -0.62009417, -0.50488752,
        -0.52286938]])

In [18]:
dbscan = DBSCAN(eps=1.8, min_samples=8)
dbscan.fit(X)

DBSCAN(eps=1.8, min_samples=8)

In [19]:
#Noisy samples are given the label -1.
dbscan.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1, -1, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [20]:
cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])

In [21]:
cl

cluster
0          0
1          0
2          0
3          0
4          0
..       ...
435        0
436        0
437        0
438        0
439        0

[440 rows x 1 columns]

In [24]:
cluster= pd.concat([df,cl],axis=1)

In [25]:
cluster

Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicassen  cluster
0    12669   9656     7561     214              2674        1338        0
1     7057   9810     9568    1762              3293        1776        0
2     6353   8808     7684    2405              3516        7844        0
3    13265   1196     4221    6404               507        1788        0
4    22615   5410     7198    3915              1777        5185        0
..     ...    ...      ...     ...               ...         ...      ...
435  29703  12051    16027   13135               182        2204        0
436  39228   1431      764    4510                93        2346        0
437  14531  15488    30243     437             14841        1867        0
438  10290   1981     2232    1038               168        2125        0
439   2787   1698     2510      65               477          52        0

[440 rows x 7 columns]

In [30]:
cluster[cluster['cluster']==-1]

Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicassen  cluster
23    26373  36423    22019    5154              4337       16523       -1
47    44466  54259    55571    7782             24171        6465       -1
61    35942  38369    59598    3254             26701        2017       -1
65       85  20959    45828      36             24231        1423       -1
71    18291   1266    21042    5373              4173       14472       -1
85    16117  46197    92780    1026             40827        2944       -1
86    22925  73498    32114     987             20070         903       -1
87    43265   5025     8117    6312              1579       14351       -1
92     9198  27472    32034    3232             18906        5130       -1
93    11314   3090     2062   35009                71        2698       -1
103   56082   3504     8906   18028              1480        2498       -1
125   76237   3473     7102   16538               778         918       -1
181  112151  29627    18148   16745              4948        8550       -1
183   36847  43950    20170   36534               239       47943       -1
211   12119  28326    39694    4736             19410        2870       -1
251    6134  23133    33586    6746             18594        5121       -1
325   32717  16784    13626   60869              1272        5609       -1
333    8565   4980    67298     131             38102        1215       -1
427   31012  16687     5429   15082               439        1163       -1